# Generated by Django 6.0.4 on 2026-05-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sport', models.CharField(max_length=100)),
                ('capacite_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_surface', models.CharField(choices=[('gazon', 'Gazon'), ('synthetique', 'Synthétique'), ('parquet', 'Parquet'), ('terre', 'Terre battue')], max_length=20)),
                ('disponibilite', models.BooleanField(default=True)),
                ('type_sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terrains', to='reservations.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.joueur')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.terrain')),
            ],
        ),
    ]
